# Generated by Django 5.1.7 on 2025-03-19 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
