# Generated by Django 4.2.20 on 2025-03-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
