# Generated by Django 4.2.20 on 2025-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtrip',
            name='flight',
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='aircraft',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='airline',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='trip_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
