# Generated by Django 4.2.20 on 2025-03-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_savedtrip_flight_savedtrip_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_in', to='flights.flight'),
        ),
    ]
