# Generated by Django 4.2.20 on 2025-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_savedtrip_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtrip',
            name='aircraft',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='airline',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
