# Generated by Django 5.1.7 on 2025-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
