# Generated by Django 5.1.7 on 2025-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_available_seats_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
    ]
