# Generated by Django 3.2.25 on 2025-03-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20250316_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(default='economy', max_length=50),
        ),
    ]
