# Generated by Django 5.1.7 on 2025-03-19 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Flight Number')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Return Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Current Price')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Original Price')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Price')),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('airline_company', models.CharField(blank=True, max_length=100, null=True)),
                ('class_of_service', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='confirmed', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-departure_date'],
            },
        ),
    ]
